/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1a1c1c",
        "on-secondary-container": "#0f6d00",
        "on-tertiary-fixed": "#261a00",
        "surface-tint": "#c8c6c5",
        "on-primary-container": "#7e7d7d",
        "on-primary-fixed-variant": "#474646",
        "primary": "#c8c6c5",
        "surface-bright": "#37393a",
        "primary-container": "#121212",
        "outline": "#8e9192",
        "on-surface-variant": "#c4c7c7",
        "on-surface": "#e2e2e2",
        "surface-container-highest": "#333535",
        "surface-container-high": "#282a2b",
        "background": "#121414",
        "on-secondary-fixed-variant": "#095300",
        "primary-fixed": "#e5e2e1",
        "inverse-on-surface": "#2f3131",
        "surface-container": "#1e2020",
        "surface-container-lowest": "#0c0f0f",
        "secondary": "#d7ffc5",
        "on-tertiary-container": "#a07700",
        "error-container": "#93000a",
        "inverse-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "surface": "#121414",
        "on-primary-fixed": "#1c1b1b",
        "outline-variant": "#444748",
        "secondary-container": "#2ff801",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#79ff5b",
        "on-error": "#690005",
        "secondary-fixed-dim": "#2ae500",
        "tertiary-fixed-dim": "#fbbc00",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-background": "#e2e2e2",
        "tertiary": "#fbbc00",
        "on-primary": "#313030",
        "tertiary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#c8c6c5",
        "surface-dim": "#121414",
        "on-secondary": "#053900",
        "on-tertiary": "#402d00",
        "on-secondary-fixed": "#022100",
        "tertiary-container": "#1a1100",
        "surface-variant": "#333535",
        "inverse-primary": "#5f5e5e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "base": "8px",
        "touch-target": "48px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
        "status-label": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-critical": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-mono": ["20px", { "lineHeight": "24px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "status-label": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-critical": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
